# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "f1978fb0820d62282071fdd8bea58214"
application_url = "https://ecology-smoking-crock.ngrok-free.dev"
embedded = true
name = "Stockative"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products"

[webhooks]
api_version = "2026-10"

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/uninstalled"
  topics = [ "app/uninstalled" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/scopes_update"
  topics = [ "app/scopes_update" ]

[auth]
redirect_urls = [ "https://ecology-smoking-crock.ngrok-free.dev/auth/callback" ]

[build]
automatically_update_urls_on_dev = true
